# Generated by Django 5.2.6 on 2025-09-22 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=63, verbose_name='Тема')),
                ('difficulty', models.CharField(choices=[('easy', 'Простая'), ('medium', 'Средняя'), ('hard', 'Тяжелая')], max_length=6, verbose_name='Сложность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('estimated_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Расчетное время')),
                ('start_date', models.DateTimeField(verbose_name='Дата запуска')),
            ],
        ),
    ]
