# Generated by Django 5.2.6 on 2025-09-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_task_assigned_to_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='related_tasks',
            field=models.ManyToManyField(blank=True, to='tasks.task', verbose_name='Связанные задачи'),
        ),
    ]
